---
version: '3'
services:
  GEANT4:
    image: davidsarria/geant4_10_7_3:jammy
    build:
      context: .
      dockerfile: "./Dockerfile.technical"
    restart: 'no'
    container_name: GEANT4
    volumes:
      - "./interface:/interface"
      - "./output:/TGF-ATMOS-ABSORPTION/build/output_ascii"
    ports:
      - "127.0.0.10:8080:8080"
    # Default command used when running `docker-compose up`
    # 10000000 15 : parameters are number of initial photons (10000000) and TGF source altitude (15 km)
    command: >
      bash -c "
      source /geant4/geant4_install_10.07.p03/bin/geant4.sh
      && pwd
      && ls
      && echo ' '
      && ls /TGF-ATMOS-ABSORPTION/
      && mkdir -p /TGF-ATMOS-ABSORPTION/build/output_ascii || true
      && cd /TGF-ATMOS-ABSORPTION/build
      && cmake ../
      && make -j4
      && ls
      && ./TGF_Propa 10000000 15
      "
      
